---
- name: App Infrastructure Provisioned on AWS
  hosts: localhost
  module_defaults:
    group/aws:
      aws_profile: default
  
  tasks:
    - name: Keypair exists
      amazon.aws.ec2_key:
        name: roysahar-ansible-keypair
        file_name: ~/.ssh/roysahar-ansible-keypair

    - name: Web server provisioned on AWS
      amazon.aws.ec2_instance:
        name: roysahar-CICDFinalExe-webserver
        key_name: roysahar-ansible-keypair
        vpc_subnet_id: subnet-07d6bb7b15ccc8452
        instance_type: t2.medium
        security_group: sg-053cc618d97b86596
        network:
          assign_public_ip: true
        image_id: ami-053a45fff0a704a47
        tags:
          Owner: roysahar
      register: ec2_result
    
    - name: Instance's public IP is in the inventory and in the host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groups: webservers
      loop: "{{ ec2_result.instances }}"